### PR TITLE
Upgraded to webpack-blocks@1.x

### PR DESCRIPTION
**Pull request by serhii-shvaher**
Fixes: #22

### CODE REVIEW

**Comment by serhii-shvaher** [comment]
@diegohaz How do you test this block with real webpack build?

**Comment by artemjackson** [comment]
Oh, what is it? - PR that hangs half a year!

The project is dead.

**Comment by diegohaz** [comment]
I'm sorry. I didn't notice the notification at that time. Will have a look.

@artemjackson Do you want to help?

**Comment by diegohaz** [comment]
Released in v0.3.0

Thank you, @SergeyShvager

**Pull request merged**
